apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vacation-gallery-uploads
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.uploads.storageSize }}
